kind: Deployment
apiVersion: extensions/v1beta1 

metadata:
  name: blackbox-tests-api

spec:
  replicas: {{.Values.global.replicaCount}}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: blackbox-tests-api
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: blackbox-tests-api
          persistentVolumeClaim:
            claimName: blackbox-tests-api
      containers:
        - name: pytest
{{- if typeIs "float64" .Values.global.image.tag  }}{{/* https://github.com/kubernetes/helm/issues/1707 */}}
          image: {{.Values.global.image.repository}}:{{.Values.global.image.tag | printf "%0.f" }}
{{- else }}
          image: {{.Values.global.image.repository}}:{{.Values.global.image.tag}}
{{- end }}
          args:
            - "iterate"
            - "pytest"
            - "-n 4"
            - "--timeout 15"
            - "--disable-pytest-warnings"
            - "-r a"
            - "tests/test_api.py"
          volumeMounts:
            - name: blackbox-tests-api
              mountPath: /opt/logs
              readOnly: false
          env:
            - name: OS_AUTH_URL
              value: {{ .Values.global.openstack.auth_url | quote }}
            - name: OS_IDENTITY_API_VERSION
              value: {{ .Values.global.openstack.identity_api_version | quote }}
            - name: OS_VOLUME_API_VERSION
              value: {{ .Values.global.openstack.volume_api_version | quote }}
            - name: OS_USERNAME
              value: {{ .Values.global.openstack.username | quote }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ .Values.global.openstack.user_domain_name | quote }}
            - name: OS_PROJECT_NAME
              value: {{ .Values.global.openstack.project_name | quote }}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{ .Values.global.openstack.project_domain_name | quote }}
            - name: OS_REGION_NAME
              value: {{ .Values.global.openstack.region_name | quote }}
            - name: VC_USERNAME
              value: {{ .Values.global.vcenter.username | quote }}
            - name: API_BILLING_URL
              value: {{ .Values.billing_url | quote }}
            - name: API_LYRA_URL
              value: {{ .Values.lyra_url | quote }}
            - name: API_ARC_URL
              value: {{ .Values.arc_url | quote }}
            - name: API_IRONIC_URL
              value: {{ .Values.ironic_url | quote }}
            - name: API_SECRET_ID
              value: {{ .Values.secret_id | quote }}
            - name: API_LIMES_URL
              value: {{ .Values.limes_url | quote }}
            - name: API_ELEKTRA_URL
              value: {{ .Values.elektra_url | quote }}
            - name: API_VC_NAMES
              value: {{ .Values.vcenter_names | quote }}
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: STATSD_PREFIX
              value: "blackbox-api"
            - name: SLEEP_ITERATE
              value: {{ .Values.sleep.iterate | quote }}
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blackbox-tests-api
                  key: os.password
            - name: VC_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: blackbox-tests-api
                  key: vc.password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: blackbox.DSN

          livenessProbe:
            exec:
              command:
              - pytest
              - --version
            timeoutSeconds: 5
            periodSeconds: 15
            initialDelaySeconds: 15
          readinessProbe:
            exec:
              command:
              - pytest
              - --version
            timeoutSeconds: 5
            periodSeconds: 15
            initialDelaySeconds: 15

        - name: statsd
          image: prom/statsd-exporter:v0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.global.port_metrics}}