{{- if .Values.maia.enabled }}
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: maia-seed
  labels:
    component: maia
spec:
  requires:
#  - keystone-seed
  - monsoon3/domain-cc3test-seed
  - monsoon3/domain-ccadmin-seed

  roles:
  - monitoring_viewer
  - monitoring_admin

  services:
  - name: maia
    type: metrics
    description: Expose Prometheus metrics as multi-tenant OpenStack service
    endpoints:
    - interface: public
      region: {{.Values.global.region}}
      url: '{{.Values.maia.endpoint_protocol_public}}://{{.Values.maia.endpoint_host_public}}:{{.Values.maia.endpoint_port_public}}/api/v1'

  domains:
  - name: {{.Values.maia.service_user.user_domain_name}}
    users:
    - name: {{.Values.maia.service_user.name}}
      description: 'Maia API User'
      password: {{ .Values.maia.service_user.password | quote }}
      roles:
      - project: {{.Values.maia.service_user.project_name}}
        role: service

  - name: ccadmin
    projects:
    - name: master
      roles:
      - group: CCADMIN_CLOUD_ADMINS
        role: monitoring_admin
      - group: CCADMIN_DOMAIN_ADMINS
        role: monitoring_admin
      - group: CCADMIN_MONITORING_USERS
        role: monitoring_viewer

  - name: cc3test
    groups:
    - name: CC3TEST_DOMAIN_ADMINS
      roles:
      - project: admin
        role: monitoring_admin

{{- end }}
