kind: Deployment
apiVersion: extensions/v1beta1 

metadata:
  name: blackbox-tests-datapath

spec:
  replicas: {{.Values.global.replicaCount}}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: blackbox-tests-datapath
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: blackbox-tests-datapath
          persistentVolumeClaim:
            claimName: blackbox-tests-datapath
        - name: blackbox-jump-key
          secret:
            secretName: blackbox-tests-datapath
            items:
              - key: jump.key
                path: authorized_keys.health
                mode: 0600
      containers:
        - name: pytest
{{- if typeIs "float64" .Values.global.image.tag  }}{{/* https://github.com/kubernetes/helm/issues/1707 */}}
          image: {{.Values.global.image.repository}}:{{.Values.global.image.tag | printf "%0.f" }}
{{- else }}
          image: {{.Values.global.image.repository}}:{{.Values.global.image.tag}}
{{- end }}
          args:
            - "iterate"
            - "pytest"
            - "-n 4"
            - "--timeout 30"
            - "--disable-pytest-warnings"
            - "-r a"
            - "tests/test_datapath.py"
          volumeMounts:
            - name: blackbox-tests-datapath
              mountPath: /opt/logs
              readOnly: false
            - name: blackbox-jump-key
              mountPath: /opt/keys
              readOnly: true
          env:
            - name: OS_AUTH_URL
              value: {{ .Values.global.openstack.auth_url | quote }}
            - name: OS_IDENTITY_API_VERSION
              value: {{ .Values.global.openstack.identity_api_version | quote }}
            - name: OS_VOLUME_API_VERSION
              value: {{ .Values.global.openstack.volume_api_version | quote }}
            - name: OS_USERNAME
              value: {{ .Values.global.openstack.username | quote }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ .Values.global.openstack.user_domain_name | quote }}
            - name: OS_PROJECT_NAME
              value: {{ .Values.global.openstack.project_name | quote }}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{ .Values.global.openstack.project_domain_name | quote }}
            - name: OS_REGION_NAME
              value: {{ .Values.global.openstack.region_name | quote }}
            - name: JUMP_URL
              value: {{ .Values.global.jump.url | quote }}
            - name: JUMP_USER
              value: {{ .Values.global.jump.user | quote }}
            - name: DATAPATH_JUMP_HOST_FLOAT_IP
              value: {{ .Values.jump_host_floating_ip | quote }}
            - name: DATAPATH_SERVER_FIXED_IPS
              value: {{ .Values.server_fixed_ips | quote }}
            - name: DATAPATH_SERVER_FLOAT_IPS
              value: {{ .Values.server_floating_ips | quote }}
            - name: DATAPATH_SERVER_DNS_NAMES
              value: {{ .Values.server_dns_names | quote }}
            - name: DATAPATH_NFS_SERVER_FLOAT_IPS
              value: {{ .Values.server_nfs_floating_ips | quote }}
            - name: DATAPATH_LBAAS_FLOAT_IPS
              value: {{ .Values.lbaas_floating_ips | quote }}
            - name: DATAPATH_BIND_IPS
              value: {{ .Values.bind_ips | quote }}
            - name: DATAPATH_UNBOUND_IPS
              value: {{ .Values.unbound_ips | quote }}
            - name: DATAPATH_HIDDEN_MASTER
              value: {{ .Values.hidden_master | quote }}
            - name: DATAPATH_REGIONAL_PTR
              value: {{ .Values.regional_ptr | quote }}
            - name: DATAPATH_TSIG_KEY
              value: {{ .Values.tsig_key | quote }}
            - name: DATAPATH_AD_NODES
              value: {{ .Values.ad_nodes | quote }}
            - name: DATAPATH_AD_DNS
              value: {{ .Values.ad_dns | quote }}
            - name: DATAPATH_S4_FIPS
              value: {{ .Values.s4_fips | quote }}
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: STATSD_PREFIX
              value: "blackbox-datapath"
            - name: SLEEP_ITERATE
              value: {{ .Values.sleep.iterate | quote }}
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blackbox-tests-datapath
                  key: os.password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: blackbox.DSN
          livenessProbe:
            exec:
              command:
              - pytest
              - --version
            timeoutSeconds: 5
            periodSeconds: 15
            initialDelaySeconds: 15
          readinessProbe:
            exec:
              command:
              - pytest
              - --version
            timeoutSeconds: 5
            periodSeconds: 15
            initialDelaySeconds: 15

        - name: statsd
          image: prom/statsd-exporter:v0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.global.port_metrics}}