kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: secgroup-entanglement-exporter
  labels:
    system: openstack
    type: api
    component: neutron
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: Recreate # not a critical component
  selector:
    matchLabels:
      name: secgroup-entanglement-exporter
  template:
    metadata:
      labels:
        name: secgroup-entanglement-exporter
{{ tuple . "neutron" "secgroup-entanglement-exporter" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      containers:
        - name: exporter
          image: {{ default "hub.global.cloud.sap" .Values.global.imageRegistry }}/{{ default "monsoon/secgroup-entanglement-exporter" .Values.secgroup_entanglement_exporter.image_name }}:{{.Values.secgroup_entanglement_exporter.image_tag}}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_URI
              value: "postgresql://{{ default .Release.Name .Values.global.dbUser }}:{{ .Values.global.dbPassword }}@{{include "neutron_db_host" .}}:{{.Values.global.postgres_port_public | default 5432}}/{{ default .Release.Name .Values.postgresql.postgresDatabase}}?sslmode=disable"
            - name: LISTEN_ADDRESS
              value: ":9102"
          ports:
            - name: metrics
              containerPort: 9102
