apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: elasticsearch
#  annotations:
#    kubernetes.io/change-cause: {{.Values.cluster_deployment_reason}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: elasticsearch
      annotations:
        checksum/elasticsearch-etc-configmap.yaml: {{ include "hermes/templates/elasticsearch-etc-configmap.yaml" . | sha256sum }}
# better delete the deployment before redeploying this after changes to the init section to make sure it really gets updated
# copy the config to some real dir as elasticsearch seems to have problems with a kube mounted configmap as -Epath.conf
# use the data volume for this as it will survive the init container run
# the scripts subdir is created as otherwise elasticsearch will complain about it being missing
        pod.alpha.kubernetes.io/init-containers: '[
        {
            "name": "init",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sh", "-c", "chown 1000:1000 /data/ && rm -rf /data/es-config && mkdir /data/es-config && cp /hermes-etc/* /data/es-config && mkdir /data/es-config/scripts"],
            "volumeMounts": [
                {
                  "name": "data",
                  "mountPath": "/data"
                },
                {
                  "name": "hermes-etc",
                  "mountPath": "/hermes-etc"
                }
            ]
        }
    ]' 
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: hermes-etc
          configMap:
            name: elasticsearch-etc
        - name: data
          persistentVolumeClaim:
            claimName: hermes-elasticsearch
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:{{.Values.hermes_image_version_elasticsearch}}
          imagePullPolicy: IfNotPresent
          command:
            - elasticsearch
          args:
            # read the config from the provided real config
            - "-Epath.conf=/data/es-config/"
          env:
            # we still have to tell elasticsearch where to find out jvm.options
            - name: ES_JVM_OPTIONS
              value: "/data/es-config/jvm.options"
          volumeMounts:
# this is not needed anymore as we copy the contents to the data volume in the init container already
#            - name: hermes-etc
#              mountPath: /hermes-etc
            - name: data
              mountPath: /data
