{{- if .Release.IsUpgrade }}
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: keystone-seed
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  roles:
  - admin
  - member
  - service
  - cloud_identity_viewer

  regions:
  - id: af
    description: 'Africa'
  - id: af-za-1
    description: 'South Africa - Cape Town'
    parent_region: af
  - id: ap
    description: 'Asia/Pacific'
  - id: ap-ae-1
    description: 'UAE - Dubai'
    parent_region: ap
  - id: ap-au-1
    description: 'Australia - Sydney'
    parent_region: ap
  - id: ap-cn-1
    description: 'China - Shanghai'
    parent_region: ap
  - id: ap-in-1
    description: 'India - New Delhi'
    parent_region: ap
  - id: ap-jp-1
    description: 'Japan - Tokyo'
    parent_region: ap
  - id: ap-jp-2
    description: 'Japan - Osaka'
    parent_region: ap
  - id: ap-sa-1
    description: 'Saudi Arabia - Riyadh'
    parent_region: ap
  - id: ap-sg-1
    description: 'Singapore'
    parent_region: ap
  - id: eu
    description: 'Europe'
  - id: eu-de-1
    description: 'Germany - Walldorf/Rot'
    parent_region: eu
  - id: eu-de-2
    description: 'Germany - Frankfurt'
    parent_region: eu
  - id: eu-nl-1
    description: 'Netherlands - Amsterdam'
    parent_region: eu
  - id: eu-ru-1
    description: 'Russia - Moscow'
    parent_region: eu
  - id: na
    description: 'North America'
  - id: na-ca-1
    description: 'Canada - Toronto'
    parent_region: na
  - id: na-us-1
    description: 'US East - Newtown Square/Sterling/Ashburn'
    parent_region: na
  - id: na-us-2
    description: 'US Mid - Colorado'
    parent_region: na
  - id: na-us-3
    description: 'US Mid - Chandler AZ'
    parent_region: na
  - id: la
    description: 'Latin America'
  - id: la-br-1
    description: 'Brazil - Sao Paolo'
    parent_region: la
  - id: staging
    description: 'Staging'
    parent_region: eu
  - id: qa-de-1
    description: 'QA Germany - Walldorf/Rot'
    parent_region: eu

  services:
  - name: keystone
    type: identity
    description: Openstack Identity

  domains:
  - name: Default
    id: default
    description: Openstack Internal Domain
    enabled: true
    users:
    - name: admin
      description: Openstack Cloud Administrator
      enabled: true
      roles:
      - domain: Default
        role: admin
      - project: admin
        role: admin
      - project: service
        role: admin

    groups:
    - name: administrators
      description: Administrators
      roles:
      - domain: Default
        role: admin
      - project: admin
        role: admin
      - project: service
        role: admin
      users:
      - admin
    - name: members
      description: Members
      roles:
      - domain: Default
        role: member
    projects:
    - name: admin
      description: Administrator Project
    - name: service
      description: Services Project
{{- end }}
