global:
  tld: DEFINED_IN_REGION_CHART
  region: DEFINED_IN_REGION_CHART
  imageRegistry: DEFINED_IN_REGION_CHART

debug: false

species: swift-storage

imageRegistry_org: monsoon
imageRegistry_repo: swift

# image version of Swift image
# the version should follow the format openstackreleasename-versionnumber
# e.g. mitaka-12345
image_version: DEFINED_BY_PIPELINE

# image version of auxiliary nginx bundled with dumb-init
image_version_nginx: '1.10.2-alpine'

# image versions of auxiliary images from other sources
image_version_auxiliary_memcached: '1.4.33-alpine'
image_version_auxiliary_memcached_exporter: 'v0.3.0'
image_version_auxiliary_statsd_exporter: 'v0.5.0'

# shared secrets and credentials
hash_path_prefix: DEFINED_IN_REGION_CHART
hash_path_suffix: DEFINED_IN_REGION_CHART

# health check only
dispersion_auth_url: DEFINED_IN_REGION_CHART
dispersion_password: DEFINED_IN_REGION_CHART

# Enable cluster health checks: https://github.com/sapcc/swift-health-statsd
health_statsd: true

# Enable prometheus probing
probing: true

# Object Server Configurations
object_replicator_concurrency: 2
object_updater_concurrency: 2

# If the swift cluster is shared across multiple openstack clusters, one can
# start multiple proxy deployments connecting to the different keystone backends
clusters:
  - name: DEFINED_IN_REGION_CHART
    # Only one cluster should seed its endpoints to keystone
    seed: DEFINED_IN_REGION_CHART
    endpoint_host: DEFINED_IN_REGION_CHART
    proxy_public_ip: DEFINED_IN_REGION_CHART
    proxy_public_port: DEFINED_IN_REGION_CHART
    keystone_auth_uri: DEFINED_IN_REGION_CHART
    keystone_auth_url: DEFINED_IN_REGION_CHART
    swift_service_user: swift
    swift_service_user_domain: Default
    swift_service_project: service
    swift_service_project_domain: Default
    swift_service_password: DEFINED_IN_REGION_CHART
    sentry_dsn: DEFINED_IN_REGION_CHART
    replicas: 2
    # If there is a need to rate limit the nginx per cluster, that can be reached here
    # The limits apply to every replica within the deployment
    #rate_limit_connections: 1000
    #rate_limit_requests: 1000
    #rate_limit_burst: 1500

    # If not defined - vice president takes over
    #tls_key: "" # DEFINED_IN_REGION_CHART
    #tls_crt: "" # DEFINED_IN_REGION_CHART

    # If vice president is active:
    #sans: [repo]

    # Offer optional HTTP port only for special domains like repo.region.tld
    # proxy_public_http_port: 8080
    # sans_http: [repo]

    # S3 API Emulation
    #s3api_enabled: true

# rings (TODO: having the rings in here is insane, but --values is currently
# the only way to supply region-specific data; figure out a better way)
account_ring_base64: DEFINED_IN_REGION_CHART
container_ring_base64: DEFINED_IN_REGION_CHART
object_ring_base64: DEFINED_IN_REGION_CHART
