apiVersion: batch/v1
kind: Job
metadata:
  name: glance-migration-job
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: glance
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
      annotations:
        chart-version: {{.Chart.Version}}
        checksum/etc-configmap.conf: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        checksum/bin-configmap.conf: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: glance-migration
          image: {{.Values.global.imageRegistry}}/{{.Values.global.imageNamespace}}/ubuntu-source-glance-api:{{.Values.image_version}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/db-migrate"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Name }}-postgresql
          volumeMounts:
            - mountPath: /glance-etc
              name: glance-etc
            - mountPath: /container.init
              name: glance-bin
              defaultMode: 0755
      volumes:
        - name: glance-etc
          configMap:
            name: glance-etc
        - name: glance-bin
          configMap:
            name: glance-bin
