# Default values for registry-cache.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# remoteURL:

# tlsHostName is is used to have vice-president handle the cert
# tlsHostName:

# alternativly specify a cert and key manually
# tlsCertificate:
# tlsKey:

image:
  repository: registry
  tag: 2.6.1
  pullPolicy: IfNotPresent
service:
  name: registry
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
# externalIPs: [ 1.2.3.4 ]


persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 10Gi

