# Default values for blackbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  image:
    repository: DEFINED-IN-REGION-SECRETS
    tag: latest
  replicaCount: 1
  openstack:
    auth_url: DEFINED-IN-REGION-SECRETS
    identity_api_version: 3
    volume_api_version: 2
    username: DEFINED-IN-REGION-SECRETS
    user_domain_name: DEFINED-IN-REGION-SECRETS
    project_name: DEFINED-IN-REGION-SECRETS
    project_domain_name: DEFINED-IN-REGION-SECRETS
    region_name: DEFINED-IN-REGION-SECRETS
    password: DEFINED-IN-REGION-SECRETS
  ccloud:
    username: DEFINED-IN-REGION-SECRETS
    user_domain_name: DEFINED-IN-REGION-SECRETS
    project_name: DEFINED-IN-REGION-SECRETS
    project_domain_name: DEFINED-IN-REGION-SECRETS
  swift:
    auth_url: DEFINED-IN-REGION-SECRETS
    user: DEFINED-IN-REGION-SECRETS
    user_domain: DEFINED-IN-REGION-SECRETS
    project_name: DEFINED-IN-REGION-SECRETS
    project_id: DEFINED-IN-REGION-SECRETS
    project_domain: DEFINED-IN-REGION-SECRETS
    region_name: DEFINED-IN-REGION-SECRETS
    api_key: DEFINED-IN-REGION-SECRETS
  jump:
    url: DEFINED-IN-REGION-SECRETS
    user: DEFINED-IN-REGION-SECRETS
    key: DEFINED-IN-REGION-SECRETS
  sentry:
    dsn: DEFINED-IN-REGION_SECRET
  port_metrics: '9102'
  testAdminUser: TEST_D021500_TA
  testMemberUser: TEST_D021500_TM
