apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: domain-tempest-seed
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
  - {{.Values.global.keystoneNamespace}}/keystone-seed

  domains:
  - name: tempest
    description: 'Converged Cloud Tempest Testing'
    dns_quota:
      api_export_size: 2000
      recordset_records: 2000
      zone_records: 10000
      zone_recordsets: 10000
      zones: 1000

    projects:
    - name: admin
      description: 'Administration'
    - name: service
      description: 'Services'
    - name: tempest1
      description: 'Tempest Test Project 1'
      roles:
        - user: admin@Default
          role: cloud_dns_admin
      dns_quota:
        api_export_size: 2000
        recordset_records: 2000
        zone_records: 2000
        zone_recordsets: 2000
        zones: 200
    - name: tempest2
      description: 'Tempest Test Project 2'
      roles:
        - user: admin@Default
          role: cloud_dns_admin
      dns_quota:
        api_export_size: 2000
        recordset_records: 2000
        zone_records: 2000
        zone_recordsets: 2000
        zones: 200

    users:
    - name: admin
      description: 'Tempest Administrator'
      password: {{ .Values.tempestAdminPassword | quote }}
      roles:
      - project: admin
        role: admin
      - project: service
        role: admin
      - domain: tempest
        role: admin
    - name: tempestuser1
      description: 'Tempest Test User 1'
      password: {{ .Values.tempestAdminPassword | quote }}
      roles:
      - project: tempest1
        role: dns_admin
      - domain: tempest
        role: dns_admin
    - name: tempestuser2
      description: 'Tempest Test User 2'
      password: {{ .Values.tempestAdminPassword | quote }}
      roles:
      - project: tempest2
        role: dns_admin
      - domain: tempest
        role: dns_admin

    groups:
    - name: administrators
      description: 'Administrators'
      users:
      - admin
      roles:
      - project: admin
        role: admin
      - project: service
        role: admin
      - domain: tempest
        role: admin
