apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: project-regression-seed
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  requires:
  - monsoon3/domain-cc3test-seed

  domains:
  - name: cc3test
    description: 'Converged Cloud Testing'

    groups:
    - name: CC3TEST_DOMAIN_ADMINS
      roles:
      - project: regression
        role: admin
      - project: regression
        role: volume_admin
      - project: regression
        role: sharedfilesystem_admin
      - project: regression
        role: network_admin
      - project: regression
        role: compute_admin
      - project: regression
        role: resource_admin
      - project: regression
        role: member
      - project: regression
        role: audit_viewer

    projects:
    - name: regression
      roles:
      - user: {{.Values.global.testAdminUser}}
        role: admin
      - user: {{.Values.global.testAdminUser}}
        role: volume_admin
      - user: {{.Values.global.testAdminUser}}
        role: sharedfilesystem_admin
      - user: {{.Values.global.testAdminUser}}
        role: network_admin
      - user: {{.Values.global.testAdminUser}}
        role: compute_admin
      - user: {{.Values.global.testAdminUser}}
        role: resource_admin
      - user: {{.Values.global.testAdminUser}}
        role: member
      - user: {{.Values.global.testAdminUser}}
        role: audit_viewer
      - user: {{.Values.global.testMemberUser}}
        role: member
      network_quota:
        subnetpool: 5
        subnet: 5
        network: 5
        rbac_policy: 10
        router: 3
      networks:
      - name: private_regression_regression_cc3test
        subnets:
        - name: private_regression_regression_cc3test_sub
          cidr: 10.180.0.0/16
          ip_version: 4
      routers:
      - name: private_regression_regression_cc3test_router
        external_gateway_info:
          network: {{.Values.global.network.monsoon3}}
        interfaces:
        - subnet: private_regression_regression_cc3test_sub

