apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: elektra-seed
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
  - monsoon3/domain-default-seed
  - monsoon3/domain-bs-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-hcp03-seed
  - monsoon3/domain-hcm-seed
  - monsoon3/domain-hec-seed
  - monsoon3/domain-monsoon3-seed
  - monsoon3/domain-s4-seed
  - monsoon3/domain-wbs-seed
  - monsoon3/domain-cc3test-seed

  roles:
  - cloud_compute_admin
  - cloud_network_admin
  - cloud_dns_admin
  - cloud_image_admin
  - cloud_keymanager_admin
  - cloud_resource_admin
  - cloud_sharedfilesystem_admin
  - cloud_volume_admin

  domains:
  - name: Default
    users:
    - name: {{ default "dashboard" .Values.monsoon_openstack_auth_api_userid | quote }}
      description: 'Dashboard Service'
      password: {{ .Values.monsoon_openstack_auth_api_password | quote }}
      roles:
      - project: service
        role: service
      - project: cloud_admin@ccadmin
        role: admin
      - project: cloud_admin@ccadmin
        role: cloud_compute_admin
      - project: cloud_admin@ccadmin
        role: cloud_dns_admin
      - project: cloud_admin@ccadmin
        role: cloud_image_admin
      - project: cloud_admin@ccadmin
        role: cloud_keymanager_admin
      - project: cloud_admin@ccadmin
        role: cloud_network_admin
      - project: cloud_admin@ccadmin
        role: cloud_resource_admin
      - project: cloud_admin@ccadmin
        role: cloud_sharedfilesystem_admin
      - project: cloud_admin@ccadmin
        role: cloud_volume_admin
      - domain: Default
        role: admin
      - domain: ccadmin
        role: admin
      - domain: bs
        role: admin
      - domain: hcp03
        role: admin
      - domain: hcm
        role: admin
      - domain: hec
        role: admin
      - domain: monsoon3
        role: admin
      - domain: s4
        role: admin
      - domain: wbs
        role: admin
      - domain: cc3test
        role: admin
