nginx-ingress:
  revisionHistoryLimit: 5

  controller:
    image:
      repository: sapcc/nginx-ingress-controller
      tag: "0.12.0"

    config:
      http-snippet: |
        map $ssl_client_s_dn $ssl_client_s_dn_cn {
            default "anonymous";
            ~CN=(?<CN>[^/,\"]+) $CN;
        }
      location-snippet: |
        proxy_set_header X-REMOTE-USER $ssl_client_s_dn_cn;
      proxy-read-timeout: '300'
      proxy-body-size: '0'
      server-name-hash-bucket-size: '128'
      map-hash-bucket-size: '128'
      worker-processes: '8'
      disable-ipv6: 'true'
      ssl-redirect: 'false'

    kind: Deployment
    replicaCount: 3

    minReadySeconds: 60
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    extraArgs:
      enable-ssl-passthrough:
      annotations-prefix: ingress.kubernetes.io

    stats:
      enabled: true

    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/probe: "10254"

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

      targetPorts:
        http: http
        https: https

      # set in regional values
      externalIPs:
        - DEFINED-AS-VALUE

    defaultBackendService: "kube-system/ingress-default-backend"

    podLabels:
      app: nginx-ingress-controller

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: species
              operator: In
              values:
                - master
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-ingress-controller
            topologyKey: kubernetes.io/hostname

  statsExporter:
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi

  defaultBackend:
    enabled: true
    replicaCount: 2
    minAvailable: 1

    image:
      repository: sapcc/defaultbackend
      tag: '1.4'
      pullPolicy: IfNotPresent

    podLabels:
      app: ingress-default-backend

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
