apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-db-init
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.postgresql.postgresDatabase}};
    CREATE ROLE {{.Values.global.dbUser}}{{.Values.global.user_suffix}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.postgresql.postgresDatabase}} TO {{.Values.global.dbUser}};

    CREATE DATABASE {{.Values.global.inspectordbName}};
    CREATE ROLE {{.Values.global.inspectordbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.inspectordbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.global.inspectordbName}} TO {{.Values.global.inspectordbUser}};
