apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-db-init
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.postgresql.postgresDatabase}};
    CREATE ROLE {{.Values.global.dbUser}}{{.Values.global.user_suffix}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.postgresql.postgresDatabase}} TO {{.Values.global.dbUser}};

    CREATE DATABASE {{.Values.global.inspector_db_name}};
    CREATE ROLE {{.Values.global.inspector_db_user}} WITH ENCRYPTED PASSWORD '{{.Values.global.inspector_db_password}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.global.inspector_db_name}} TO {{.Values.global.inspector_db_user}};
