{{- if .Values.postgresql.postgresPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-db-maintain
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sql: |
    ALTER ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}';
    ALTER ROLE {{.Values.global.inspectordbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.inspectordbPassword}}';
    ALTER ROLE {{.Values.postgresql.postgresUser}} WITH ENCRYPTED PASSWORD '{{.Values.postgresql.postgresPassword}}';
{{- end }}
