apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-db-maintain
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sql: |
    ALTER ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}';
    ALTER ROLE {{.Values.global.inspector_db_user}} WITH ENCRYPTED PASSWORD '{{.Values.global.inspector_db_password}}';
    ALTER ROLE {{.Values.postgresql.postgresUser}} WITH ENCRYPTED PASSWORD '{{.Values.postgresql.postgresPassword}}';
