kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  replicas: {{ .Values.pod.replicas.pxe }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: ironic-pxe
  template:
    metadata:
      labels:
        name: ironic-pxe
{{ tuple . "ironic" "pxe" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-pxe-hash: {{ include (print $.Template.BasePath "/pxe-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ironic-tftp
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-pxe:{{.Values.image_version_ironic_pxe | default .Values.image_version | required "Please set ironic.image_version or similar"}}
          imagePullPolicy: IfNotPresent
          command: ["ptftpd", "-v", "-d", "/tftpmap.py:handle", "eth0", "/tftpboot"]
          ports:
            - name: ironic-tftp
              protocol: UDP
              containerPort: {{.Values.global.ironic_pxe_port_public}}
          volumeMounts:
            - mountPath: /tftpboot
              name: ironic-tftp
        - name: ironic-ipxe
          image: {{.Values.image_version_nginx | default "nginx:stable-alpine"}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: ironic-ipxe
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - mountPath: /srv/tftpboot
              name: ironic-tftp
            - mountPath: /etc/nginx/conf.d
              name: ironic-pxe
          livenessProbe:
            httpGet:
              path: /tftpboot
              port: ironic-ipxe
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: ironic-tftp
          persistentVolumeClaim:
            claimName: ironic-tftp-pvclaim
        - name: ironic-pxe
          configMap:
            name: ironic-pxe
            defaultMode: 0444
