kind: Service
apiVersion: v1

metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  type: NodePort
  selector:
    name: ironic-pxe
  ports:
    - name: ironic-tftp
      protocol: UDP
      port: {{.Values.global.ironic_tftp_port_public}}
      targetPort: ironic-tftp
    - name: ironic-ipxe
      protocol: TCP
      port: {{.Values.conductor.deploy.port}}
      targetPort: ironic-ipxe
  {{- if .Values.global.ironic_tftp_ip }}
  externalIPs:
    - {{.Values.global.ironic_tftp_ip}}
  {{- end }}
  sessionAffinity: "ClientIP"
